### PR TITLE
Add wake and sleep functions

### PR DESCRIPTION
**Pull request by wbjeffrey**
Added functions to wake (release deep power down) and sleep (deep power down) the flash chip.

Signed-off-by: Jeffrey Bailey <wb.jeffrey@gmail.com>

### CODE REVIEW

**Comment by daniel-thompson** [comment]
Hi Jeffrey

I've been busy reading the specs for various SPINOR devices trying to understand how this code works (partly because the algorithm you have settled on is subtly different to the one in ATCWatch and partly because neither approach makes total sense acording to the spec).

As part of that I wrote a quick program to compare the results of running RDP (0xab, single command byte) and RES (0xab, opcode, 3 dummy bytes, 8-bit signature repeated until CS goes low). On all three of the watches I tested (PineTime, Colmi P8, Senbono K9) both the wakeup commands seem to be working fine. This would appear to contradict your results since IIRC you could send the DP command and break things.

Anyhow, do you have wasptool working? If so can you run the following test (`./tools/wasptool --exec nortest.py` and post the results here I'd like to understand whether we get different results:

```
# nortest.py
import watch

spi = watch.flash._spi
cs = watch.flash._cspins[0]
mvp = watch.flash._mvp

def rw(buf):
    cs(0)
    spi.write_readinto(buf, buf)
    cs(1)
    return list(buf)

def rdid():
    mvp[0] = 0x9f
    return rw(mvp[:4])

def dp():
    mvp[0] = 0xb9
    return rw(mvp[:1])

def rdp():
    mvp[0] = 0xab
    return rw(mvp[:1])

def res():
    mvp[0] = 0xab
    return rw(mvp)

def test(reference=None):
    results = [ (cmd.__name__, cmd()) for cmd in (rdid, dp, rdid, rdp, rdid, dp, rdid, res, rdid, res) ]
    # Only print the results if they are different from the previous run
    if results != reference:
        for c, r in results:
            print(c, r)
    return results

def runit(n):
    reference = test()
    for i in range(n):
        reference = test(reference)

runit(100)
```

**Comment by daniel-thompson** [comment]
PS If you are curious this is what I see on my PineTime (although I had to modify the `~-~` seperators to get valid markdown):

~~~
stingray$ ./tools/wasptool --exec nortest.py --device PineTime
Preparing to run nortest.py:
[##################################################] 100% 
~-~
rdid [0, 11, 64, 22]
dp [0]
rdid [0, 0, 0, 0]
rdp [0]
rdid [0, 11, 64, 22]
dp [0]
rdid [0, 0, 0, 0]
res [0, 0, 0, 0, 21, 21]
rdid [0, 11, 64, 22]
res [0, 0, 0, 0, 21, 21]
~-~
~~~

The main point of note is that, in the above, RDP is just as effective at RES at waking up the device and getting it to respond to the RDID command.

**Comment by wbjeffrey** [comment]
I ran your test and I get exactly the same results you did. This doesn't surprise me at all.

One of the major things I ran into was what I suspect we are seeing here. I could run wasptool to connect to the console and I did many tests that way. Every reasonable test to wake up the flash actually succeeded when tested that way. Then I would put the exact same code into wasp-os in the appropriate place, flash the firmware, and it would fail. Every time. I wasted days of time chasing this behavior down. I don't know what is going on, but there is something different in the wasp-os bring-up of the HW vs running things via the connected console. The only thing that didn't fail during wasp-os boot, when the flash is in deep power down, is the approach I submitted. 

I'm not sure what you are referring to as being different in my code vs ATCWatch, unless we are looking at different ATCWatch code bases. The only thing I added was the iteration count and test for prevention of an infinite loop like we discussed. Unless you are referring to me splitting the functionality into 2 methods instead of one that takes a flag. If so, I just thought it reads better and is more understandable this way.

Oh, and in reviewing my patch, I found a missing buffer initializer line which I've added, tested, and pushed to my fork.

I agree with your statement that the approach doesn't seem supported by the HW data sheet(s). However, following the specs in the data sheets just doesn't seem to work. And I would speculate that might be why ATCWatch has a different approach. Just a guess, but there might be some timing/jitter SPI issues and perhaps the 0x15 values were empirically determined to indicate success. I can tell you this - the code always seems to take 2 iterations to wake the flash and get the required response during firmware boot.

I don't know what else to tell you on this. Of course it's up to you on how to proceed with this patch. I do know it isn't the first time I've worked on HW that doesn't behave exactly the way the docs say it should.

**Comment by daniel-thompson** [comment]
> I'm not sure what you are referring to as being different in my code vs ATCWatch,
> unless we are looking at different ATCWatch code bases.

The ATCwatch code relies on the spinor protocol being single duplex and, each loop, writes 4 bytes (ignoring what should be hi-z from the spinor) and then reads the following three bytes (probably issuing zeros to the spinor). I suspect it always suceeds on the first loop (largely because what is does with the chip select when it loops looks so wrong).

Your code loops doing full duplex 4 byte transactions although because it doesn't toggle chip select it will appears to the spinor like one big transaction (8 bytes long in the case when you go round the loop twice). In other words I think your code succeeds during the second iteration when it reads the fifth byte as 0x15.

Anyhow, thanks to the rest of your comment I have, for the first time managed to reproduce the Init SPINOR FAILED problem (which is "cured" if I run a variant of the diagnostics I shared earlier). To be honest it feels to me like there is a glitch on the nRF52832 side running the first 0xAB wake up transaction. I'll let you know...

**Comment by daniel-thompson** [comment]
> One of the major things I ran into was what I suspect we are seeing here. I could run wasptool to connect to the console and I did many tests that way. Every reasonable test to wake up the flash actually succeeded when tested that way. Then I would put the exact same code into wasp-os in the appropriate place, flash the firmware, and it would fail. Every time.

I have chased this down the difference between strings and bytestrings (e.g. spi.write('\xAB') and spi.write(b'\xAB'). To save space the parser on the device will treat these as the same (e.g. both strings are treated as binary instead of the regular string being encoded in something like UTF-8) but it looks like frozen modules are stricter about marking binary strings correctly.

In other words I think when run from a frozen module then spi.write('\xAB') does not actually send out 0xAB (but spi.write(b'\xAB') does).

Now we understand what is going on I'll take this patch shortly but with a substantial simplification to the wake() method. I have watches with two different flash manufactures and all testing looks good for me.

Thanks for the patch... and for the additional clues that helped understand what is going on.

**Comment by daniel-thompson** [comment]
Merged. Thanks.

**Comment by wbjeffrey** [comment]
Wow. That's a real 'gotcha' in the micropython environment. Congrats for finding it. The behavior difference was driving me a bit crazy. Glad you could simplify the code.

**Pull request closed without merging**
